openapi: '3.0.0'
info:
  $include: ./info/index.yaml
servers:
  - url: '{protocol}://localhost:3001/api'
    description: Development API Server
    variables:
      protocol:
        enum:
          - http
          - https
        default: http

paths:
  $include: ./paths/index.yaml

components:
  $include: ./components/index.yaml

