version: '3.7'

services:

  openldap:
    container_name: openldap
    build:
      context: ./services/openldap
      dockerfile: Dockerfile
    env_file: ./services/openldap/openldap.env
    ports:
      - "389:389"

  keycloak:
    container_name: keycloak
    build:
      context: ./services/keycloak
      dockerfile: Dockerfile
    ports:
      - "10001:8080"
    volumes:
      - .:/export
    env_file: ./services/keycloak/keycloak.env

  serendipity-api:
    container_name: serendipity-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./h2:/h2
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:/h2/serendipity
      AUTO_SERVER: 1
      AUTO_SERVER_PORT: 9091
      DB_CLOSE_DELAY: -1
