version: '3.7'

services:
  openldap:
    container_name: openldap
    build:
      context: ./services/openldap
      dockerfile: Dockerfile
    env_file: ./services/openldap/openldap.env
    ports:
      - "389:389"

  keycloak:
    container_name: keycloak
    build:
      context: ./services/keycloak
      dockerfile: Dockerfile
    env_file: ./services/keycloak/keycloak.env
    ports:
      - "10001:8080"

  serendipity-api:
    container_name: serendipity-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./serendipity-api.env
    ports:
      - "3001:3001"